# Generated by Django 3.2.12 on 2022-02-17 07:34

import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(240)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='story_image', verbose_name='Images')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish'), ('draft', 'draft'), ('archived', 'archived')], default='draft', max_length=150, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('expiration_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 18, 7, 34, 14, 964973), verbose_name='Expiration Time')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('read', models.ManyToManyField(blank=True, related_name='read', to=settings.AUTH_USER_MODEL)),
                ('saved', models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Story',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tag name')),
                ('Story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story')),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
