# Generated by Django 3.2.12 on 2022-02-16 09:39

import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('content', ckeditor.fields.RichTextField(validators=[django.core.validators.MaxLengthValidator(240)])),
                ('status', models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish'), ('draft', 'draft'), ('archived', 'archived')], default='draft', max_length=150)),
                ('is_read', models.BooleanField(default=False)),
                ('expiration_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 17, 9, 39, 12, 455687))),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 2, 16, 9, 39, 12, 455743))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 9, 39, 12, 455758))),
                ('saved', models.ManyToManyField(blank=True, default=False, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Story',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tag name')),
                ('Story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.story')),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
