# Generated by Django 3.2.12 on 2022-02-17 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 18, 6, 5, 25, 226457)),
        ),
        migrations.AlterField(
            model_name='story',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
