# Generated by Django 3.2.12 on 2022-02-17 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 18, 5, 34, 2, 778662), verbose_name='Expiration Time'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish'), ('draft', 'draft'), ('archived', 'archived')], default='draft', max_length=150, verbose_name='Status'),
        ),
    ]
