# Generated by Django 3.2.12 on 2022-02-16 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 17, 9, 47, 5, 404960)),
        ),
        migrations.AlterField(
            model_name='story',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
