# Generated by Django 3.2.12 on 2022-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_story_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Expiration Time'),
        ),
    ]
