# Generated by Django 3.2.12 on 2022-02-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220216_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 17, 9, 48, 45, 585060)),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
