# Generated by Django 3.2.12 on 2022-02-17 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220217_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 18, 5, 34, 56, 131633), verbose_name='Expiration Time'),
        ),
    ]
