# Generated by Django 3.2.12 on 2022-02-16 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220216_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 17, 9, 49, 37, 865748)),
        ),
    ]
