# Generated by Django 3.2.12 on 2022-02-17 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_story_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 18, 7, 34, 49, 823585), verbose_name='Expiration Time'),
        ),
    ]
