# Generated by Django 4.0.2 on 2022-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_pushnotification_id_alter_story_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(default='', max_length=255, verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='story_image', verbose_name='Images'),
        ),
    ]
