# Generated by Django 4.0.2 on 2022-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_story_author_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish'), ('draft', 'draft'), ('archived', 'archived'), ('archived_deleted', 'archived_deleted')], default='draft', max_length=150, verbose_name='Status'),
        ),
    ]
