# Generated by Django 4.0.2 on 2022-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_story_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='notification_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Notification_count'),
        ),
    ]
