# Generated by Django 4.0.2 on 2022-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_story_notification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='notification_count',
            field=models.CharField(blank=True, default=0, max_length=2, null=True, verbose_name='Notification_count'),
        ),
    ]
