# Generated by Django 4.0.2 on 2022-02-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_story_notification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
