# Generated by Django 4.0.2 on 2022-02-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_story_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='archived_with_delete',
            field=models.BooleanField(default=False),
        ),
    ]
