# Generated by Django 4.0.3 on 2022-03-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_delete_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
