# Generated by Django 4.0.3 on 2022-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_story_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('publish', 'publish'), ('unpublish', 'unpublish'), ('draft', 'draft'), ('archived', 'archived')], default='draft', max_length=150, verbose_name='Status'),
        ),
    ]
