# Generated by Django 3.2.12 on 2022-02-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="provider_user_id",
        ),
    ]
