# Generated by Django 3.2.12 on 2022-02-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220218_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='(e.g +918457221548, +33123456789)', max_length=25, null=True),
        ),
    ]
