# Generated by Django 4.0.2 on 2022-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_provider_user_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_identifier_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
