# Generated by Django 4.0.2 on 2022-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_identifier_key',
            field=models.CharField(blank=True, max_length=1225, null=True),
        ),
    ]
