# Generated by Django 4.0.2 on 2022-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
